# Generated by Django 5.2.3 on 2026-08-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_due_date_todoitem_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='reminderSent',
            field=models.BooleanField(default=False),
        ),
    ]
