# Generated by Django 5.2.3 on 2025-07-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='due_date',
            new_name='dueDate',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='created_at',
        ),
    ]
