# Generated by Django 5.2.3 on 2025-07-02 15:00

import fileManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManagement', '0003_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=fileManagement.models.user_directory_path),
        ),
    ]
